name: Update Issue Comment

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! 👋
            This comment was automatically created and can be updated by the workflow.
