name: Update Issue Comment

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue dawg, We'll get back to you as soon as possible.
